# node 20 é mais eficiente que o 18 -> https://blog.rafaelgss.dev/state-of-nodejs-performance-2023#:~:text=optimized%20as%20well.-,Between%20Node.,contribute%20to%20faster%20startup%20times.
FROM node:20-alpine

WORKDIR /usr/src/app

EXPOSE 3333

CMD ["npm", "start"]
